name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential cmake git

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout pico-sdk
        run: |
          git clone https://github.com/raspberrypi/pico-sdk.git
          cd pico-sdk
          git submodule update --init

      - name: Set environment variable
        run: echo "PICO_SDK_PATH=$(pwd)/pico-sdk" >> $GITHUB_ENV
        run: echo "PICO_BOARD=pico_w" >>  $GITHUB_ENV

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make
