name: Build

on:
  - push
  - pull_request
  - workflow_dispatch

# Cancels old runs when new ones are triggered
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

# Only has read permissions to the repo
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential cmake git

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout pico-sdk
        run: |
          git clone https://github.com/raspberrypi/pico-sdk.git
          cd pico-sdk
          git submodule update --init

      - name: Set environment variable
        run: |
          echo "PICO_SDK_PATH=$(pwd)/pico-sdk" >> $GITHUB_ENV |
          echo "PICO_BOARD=pico_w" >>  $GITHUB_ENV

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Upload uf2 file
        uses: actions/upload-artifact@v2
        with:
          name: cgm_app-uf2
          path: build/cgm_app.uf2
